---
apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: ksm-scrape
  labels:
    monitoredby: aap-monitoring
spec:
  namespaceSelector:
    matchNames:
      - openshift-monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
    - port: https-main
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
